### ISSUE TITLE
False positive for disc encryption on a Mac

### ISSUE THREAD

**Issue by dryan** [Netflix-Skunkworks/stethoscope-app#87] opened 2018-12-14 20:10 UTC
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Staff member installed Stethoscope on her brand new MacBook Air. It's reporting that disc encryption is on while FileVault says it is not on.

<img width="1198" alt="screen shot 2018-12-14 at 3 00 04 pm" src="https://user-images.githubusercontent.com/15066/50025005-28e29680-ffb2-11e8-8105-7b803d44c96d.png">

* **What is the expected behavior?**

If FileVault is not enabled, disc encryption check should fail.

* **Please tell us about your environment:**

  - Stethoscope Version: 2.0.3
  - Platform:
    - [x] Mac
    - [ ] Windows
  - Browser: irrelevant

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rmcvey** [comment] 2018-12-14 20:17
Hi Dan, this issue was resolved in the 2.1.0 release. The issue is that newer Macbooks with a T2 chip are "encrypted" (though not very securely) by default so `osquery` reports them as such. We moved to checking the FileVault status instead https://github.com/Netflix-Skunkworks/stethoscope-app/blob/master/resolvers/platform/MacSecurity.js#L106

**Closed** 2019-02-13 23:01 UTC
